version: '3.8'
services:
  # migrator:
  #   build: ./backend
  #   command: npm run migrate:down && npm run migrate:up
  #   env_file:
  #     - ./backend/.env
  api:
    build: ./backend
    ports:
      - "8080:3000"
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
    depends_on:
      migrator:
        condition: service_completed_successfully
