version: '3.8'
services:
  migrator:
    build: .
    command: npm run migrate:up
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      AES_KEY: ${AES_KEY}
      AES_IV: ${AES_IV}
      ENCRYPTED_DB_PASSWORD: ${ENCRYPTED_DB_PASSWORD}
  api:
    build: .
    ports:
      - "8080:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      # Password DB akan didekripsi dari ENCRYPTED_DB_PASSWORD menggunakan AES_KEY/IV
      ENCRYPTED_DB_PASSWORD: ${ENCRYPTED_DB_PASSWORD}
      AES_KEY: ${AES_KEY}
      AES_IV: ${AES_IV}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    depends_on:
      migrator:
        condition: service_completed_successfully
