name: myapp
description: A simple chatbot application using Kolosal AI API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  onnxruntime: ^1.4.2
  flutter_dotenv: ^6.0.0
  provider: ^6.0.0
  intl: ^0.20.2
  share_plus: ^12.0.1
  fl_chart: ^1.1.1
  image_picker: ^1.2.1
  path_provider: ^2.0.15
  shared_preferences: ^2.0.15
  sqflite: ^2.2.8+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - .env
    - lib/models/umkm_forecast.onnx




